### ISSUE TITLE
Proc avionics config node error

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RP-0#775]
As stated on the KSP forums, in the ScrapYard thread:

>I'm playing with the RSS/RO/RP-0 set of mods, built from master/dev branches, along with ScrapYard built from master. I get a ton of errors in the VAB when building a vessel with the procedural avionics part that RP-0 provides:

```
[ERR 15:45:41.492] Input is null for field 'avionicsTechLevel' in config node ''
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at BaseFieldList.Save(.ConfigNode node)
   at PartModule.Save(.ConfigNode node)
   at ScrapYard.ModuleTemplateList.FindMatchingTemplate(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.ModuleTemplateList.CheckForMatch(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.InventoryPart.storeModuleNode(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.InventoryPart..ctor(.Part originPart)
   at ScrapYard.PartTracker.GetUsesForPart(.Part part, TrackType type)
   at ScrapYard.APIManager.GetUseCount_Part(.Part part, System.String type)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at KerbalConstructionTime.ScrapYardWrapper.invokeMethod(System.String methodName, System.Object[] parameters)
   at KerbalConstructionTime.ScrapYardWrapper.GetUseCount(.Part part, TrackType trackType)
   at KerbalConstructionTime.KCT_Utilities.GetBuildTime(System.Collections.Generic.List`1 parts, Boolean useInventory)
   at KerbalConstructionTime.KCT_Utilities.RecalculateEditorBuildTime(.ShipConstruct ship)
   at KerbalConstructionTime.KerbalConstructionTime.EditorRecalculation()
```
```
[ERR 15:45:40.237] Input is null for field 'avionicsTechLevel' in config node ''
   at System.Environment.get_StackTrace()
   at ConfigNode.AddValue(System.String name, System.String value)
   at BaseFieldList.Save(.ConfigNode node)
   at PartModule.Save(.ConfigNode node)
   at ScrapYard.ModuleTemplateList.FindMatchingTemplate(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.ModuleTemplateList.CheckForMatch(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.InventoryPart.storeModuleNode(System.String partName, .ConfigNode moduleNode)
   at ScrapYard.InventoryPart..ctor(.Part originPart)
   at ScrapYard.Utilities.EditorHandling.VerifyEditorShip()
   at ScrapYard.ScrapYard.VerifyEditor()
```
>This happens when the only part of the vessel is the proc avionics core.
Is this a ScrapYard error? Or does the bug lay elsewhere?

And magico13's response:

>> Is this a ScrapYard error? Or does the bug lay elsewhere?

>Yes. Both of those. Somehow the avionicsTechLevel value is null, which isn't valid, so it throws an exception. But ScrapYard should probably catch that exception and handle it. It may also be due to the way ScrapYard interacts with the module. I'm not sure of how to fix it off the top of my head and I'll likely have to set up an environment where I can reproduce it, which might not be for a while.

**Comment by DRVeyl** [comment]
avionicsTechLevel is now guaranteed to be set early in onStart, and the field is persistent, so it will be valid for any existing vessel.  Fixed.
